#include <string.h>

#include "app_message.h"
#include "config_wire.h"
#include "persist.h"
#include "palette.h"
#include "c/layers/forecast_layer.h"
#include "c/layers/status_bar.h"
#include "c/layers/loading_layer.h"
#include "c/layers/rain_radar_layer.h"
#include "c/layers/calendar_layer.h"
#include "c/layers/top_status_layer.h"
#include "c/windows/main_window.h"
#include "c/services/watch_services.h"
#include "rain_countdown.h"
#include "memory_log.h"
#include "status_line.h"
#if defined(WW_THRESHOLD_HIGHLIGHT)
#include "status_threshold.h"
#endif

// Payloads arrive split into categories that map onto screen areas (forecast
// chart, status row, radar). Each category is processed independently and the
// persist setters report real changes, so only the affected layers redraw.

typedef struct {
    SeriesId id;
    uint32_t trend_key;     // MESSAGE_KEY_* (values unchanged)
} SeriesWire;

static bool handle_forecast(DictionaryIterator *iterator, bool *forecast_dirty) {
    Tuple *temp_trend_tuple = dict_find(iterator, MESSAGE_KEY_TEMP_TREND_UINT8);
    Tuple *forecast_start_tuple = dict_find(iterator, MESSAGE_KEY_FORECAST_START);
    Tuple *num_entries_tuple = dict_find(iterator, MESSAGE_KEY_NUM_ENTRIES);
    // Render-ready, already-selected series (PKJS owns the choice). The line
    // styling that used to ride here is settings-derived and now arrives on the
    // Clay message instead — see handle_line_style below.
    Tuple *temp_min_tuple = dict_find(iterator, MESSAGE_KEY_TEMP_MIN);
    Tuple *temp_max_tuple = dict_find(iterator, MESSAGE_KEY_TEMP_MAX);

    if (!(temp_trend_tuple && forecast_start_tuple && num_entries_tuple)) {
        if (temp_trend_tuple || forecast_start_tuple || num_entries_tuple) {
            APP_LOG(APP_LOG_LEVEL_WARNING,
                    "Forecast payload incomplete (temp=%d start=%d entries=%d) — skipping",
                    temp_trend_tuple != NULL,
                    forecast_start_tuple != NULL,
                    num_entries_tuple != NULL);
        }
        return false;
    }

    // NUM_ENTRIES rides a separate tuple from the trend bytes; clamp it to the
    // trend tuple's own length so a skewed count can never size a read past
    // the array (write_data_if_changed memcmp/writes exactly this many bytes).
    int num_entries = (int) num_entries_tuple->value->int32;
    if (num_entries < 0) { num_entries = 0; }
    if (num_entries > (int) temp_trend_tuple->length) {
        num_entries = (int) temp_trend_tuple->length;
    }
#ifdef WW_ENABLE_MEMORY_LOGGING
    APP_LOG(APP_LOG_LEVEL_DEBUG, "MEM|forecast_payload|entries=%d|free=%lu|used=%lu",
            num_entries,
            (unsigned long)heap_bytes_free(),
            (unsigned long)heap_bytes_used());
#endif
    bool changed = false;
    changed |= persist_set_forecast_start((time_t) forecast_start_tuple->value->int32);
    changed |= persist_set_num_entries(num_entries);
    changed |= persist_set_temp_trend((uint8_t*) temp_trend_tuple->value->data, num_entries);
    if (temp_min_tuple) { changed |= persist_set_temp_min((int) temp_min_tuple->value->int32); }
    if (temp_max_tuple) { changed |= persist_set_temp_max((int) temp_max_tuple->value->int32); }

    // MESSAGE_KEY_* are uint32_t globals (generated by the SDK), not
    // compile-time constants, so the table must be initialized at runtime.
    const SeriesWire WIRE[] = {
        { SERIES_SECOND, MESSAGE_KEY_SECONDARY_LINE_TREND_UINT8 },
        { SERIES_THIRD,  MESSAGE_KEY_THIRD_LINE_TREND_UINT8     },
        { SERIES_BARS,   MESSAGE_KEY_BAR_TREND_UINT8            },
    };
    // Render-ready series (trend bytes only) — table-driven.
    // Element count = byte length (1 byte/elem). Empty/missing => count 0,
    // which the per-series setter treats per its own semantics (line/bar keep
    // a 0 count + stale trend; third deletes its key).
    for (unsigned w = 0; w < sizeof(WIRE) / sizeof(WIRE[0]); ++w) {
        Tuple *tt = dict_find(iterator, WIRE[w].trend_key);
        int count = tt ? (int) tt->length : 0;
        changed |= persist_series_set_trend(WIRE[w].id,
                       count ? (uint8_t*) tt->value->data : NULL, count);
    }

    *forecast_dirty |= changed;
    return true;
}

static bool handle_status(DictionaryIterator *iterator, bool *status_dirty, bool *radar_dirty) {
    Tuple *is_sleeping_tuple = dict_find(iterator, MESSAGE_KEY_IS_SLEEPING);

    if (!is_sleeping_tuple) {
        return false;
    }

    bool changed = false;
    const bool sleeping = (bool) is_sleeping_tuple->value->int16;
    changed |= persist_set_is_sleeping(sleeping);
    if (sleeping) {
        // Sleep onset latches the radar area into snooze immediately.
        // The latch is released on the wake transition by the awake check
        // in inbox_received_callback.
        *radar_dirty |= persist_set_radar_snooze(true);
    }

    *status_dirty |= changed;
    return true;
}

static uint32_t status_line_key(int line_id) {
    switch (line_id) {
        case 0: return MESSAGE_KEY_STATUS_LINE_1_UINT8;
        case 1: return MESSAGE_KEY_STATUS_LINE_2_UINT8;
        case 2: return MESSAGE_KEY_STATUS_LINE_3_UINT8;
        default: return MESSAGE_KEY_STATUS_LINE_4_UINT8;
    }
}

static bool handle_status_lines(DictionaryIterator *iterator, bool *status_dirty) {
    bool any = false;
    bool changed = false;
    for (int i = 0; i < STATUS_LINE_COUNT; i++) {
        Tuple *tuple = dict_find(iterator, status_line_key(i));
        if (!tuple) { continue; }
        any = true;
        if (tuple->type != TUPLE_BYTE_ARRAY ||
            !status_line_validate(tuple->value->data, tuple->length)) {
            // Reject atomically; the last good persisted line stays intact.
            APP_LOG(APP_LOG_LEVEL_WARNING,
                    "Status line %d invalid (%u bytes) — skipping", i + 1,
                    (unsigned) tuple->length);
            continue;
        }
        changed |= persist_set_status_line((uint8_t) i, tuple->value->data,
                                           tuple->length);
    }
    *status_dirty |= changed;
    return any;
}

#if defined(WW_THRESHOLD_HIGHLIGHT)
// Packed weather-kind threshold levels — rides the weather message next to the
// packed lines (the phone computes them; the watch has no raw AQI/wind ints).
static bool handle_status_levels(DictionaryIterator *iterator, bool *status_dirty) {
    Tuple *tuple = dict_find(iterator, MESSAGE_KEY_STATUS_LEVELS_UINT8);
    if (!tuple) { return false; }
    if (tuple->type != TUPLE_BYTE_ARRAY || tuple->length < 1) {
        APP_LOG(APP_LOG_LEVEL_WARNING,
                "Status levels tuple malformed (%u bytes) — skipping",
                (unsigned) tuple->length);
        return true;
    }
    // 2 LE bytes since UV joined the weather kinds (bits 8-9); a 1-byte value
    // (older phone JS) still reads correctly as the low byte.
    int levels = tuple->value->data[0];
    if (tuple->length >= 2) { levels |= tuple->value->data[1] << 8; }
    *status_dirty |= persist_set_status_levels(levels);
    return true;
}

// Threshold settings blob — rides the Clay message (enabled bits, colors, and
// the health-kind thresholds the watch compares live values against).
static bool handle_thresholds(DictionaryIterator *iterator, bool *status_dirty) {
    Tuple *tuple = dict_find(iterator, MESSAGE_KEY_CLAY_THRESHOLDS_UINT8);
    if (!tuple) { return false; }
    if (tuple->type != TUPLE_BYTE_ARRAY ||
        !status_threshold_settings_validate(tuple->value->data, tuple->length)) {
        // Reject atomically; the last good persisted blob stays intact.
        APP_LOG(APP_LOG_LEVEL_WARNING,
                "Threshold settings invalid (%u bytes) — skipping",
                (unsigned) tuple->length);
        return true;
    }
    *status_dirty |= persist_set_threshold_settings(tuple->value->data,
                                                    tuple->length);
    return true;
}
#endif  // WW_THRESHOLD_HIGHLIGHT

#if defined(WW_FETCH_NOTICE)
static bool handle_notice(DictionaryIterator *iterator, bool *notice_dirty) {
    Tuple *notice_tuple = dict_find(iterator, MESSAGE_KEY_NOTICE_TEXT);
    if (!notice_tuple) {
        return false;
    }
    // A CSTRING tuple; an empty string clears the overlay.
    const char *text = (notice_tuple->type == TUPLE_CSTRING)
        ? notice_tuple->value->cstring : "";
    *notice_dirty |= persist_set_notice_text(text);
    return true;
}
#endif

static bool handle_sun_events(DictionaryIterator *iterator, bool *forecast_dirty, bool *status_dirty) {
    Tuple *sun_events_tuple = dict_find(iterator, MESSAGE_KEY_SUN_EVENTS);
    if (!sun_events_tuple) {
        return false;
    }

    // Packed as one start-type byte followed by two epoch timestamps; a
    // shorter tuple is corrupt/skewed — don't read past its end.
    if (sun_events_tuple->length < (int) (1 + 2 * sizeof(time_t))) {
        return false;
    }
    uint8_t sun_event_start_type = (uint8_t) sun_events_tuple->value->uint8;
    time_t *sun_event_times = (time_t*) (sun_events_tuple->value->data + 1);
    bool changed = false;
    changed |= persist_set_sun_event_start_type(sun_event_start_type);
    changed |= persist_set_sun_event_times(sun_event_times, 2);

    // Sun events feed the chart's day/night shading and the status row.
    *forecast_dirty |= changed;
    *status_dirty |= changed;
    return true;
}

#if defined(WW_RAIN_RADAR)
static bool handle_rain_radar(DictionaryIterator *iterator, bool *radar_dirty) {
    Tuple *rain_radar_exact_tuple = dict_find(iterator, MESSAGE_KEY_RAIN_RADAR_TREND_UINT8);
    Tuple *rain_radar_area_tuple  = dict_find(iterator, MESSAGE_KEY_RAIN_RADAR_TREND_AREA_UINT8);
    Tuple *rain_radar_start_tuple = dict_find(iterator, MESSAGE_KEY_RAIN_RADAR_START);

    if (!(rain_radar_exact_tuple && rain_radar_area_tuple && rain_radar_start_tuple)) {
        if (rain_radar_exact_tuple || rain_radar_area_tuple) {
            // Partial radar payload — log and discard so persist never holds half-state.
            // RAIN_RADAR_START alone is too generic an int32 to count as radar-flavoured.
            APP_LOG(APP_LOG_LEVEL_WARNING,
                    "Rain-radar payload incomplete (exact=%d area=%d start=%d) — skipping",
                    rain_radar_exact_tuple != NULL,
                    rain_radar_area_tuple  != NULL,
                    rain_radar_start_tuple != NULL);
            return true;
        }
        return false;
    }

    bool changed = false;
    if (rain_radar_exact_tuple->length == 0) {
        // Empty array from a non-DWD provider — clear persisted radar data.
        uint8_t zeros[24] = {0};
        changed |= persist_set_rain_radar_trend(zeros, 24);
        changed |= persist_set_rain_radar_trend_area(zeros, 24);
        changed |= persist_set_rain_radar_start(0);
    } else if (rain_radar_exact_tuple->length < 24 || rain_radar_area_tuple->length < 24) {
        // Short arrays (version skew / corrupt payload) — discard rather than
        // overread the inbox and persist the trailing bytes as intensities.
        APP_LOG(APP_LOG_LEVEL_WARNING,
                "Rain-radar arrays too short (exact=%u area=%u) — skipping",
                (unsigned) rain_radar_exact_tuple->length,
                (unsigned) rain_radar_area_tuple->length);
    } else {
        changed |= persist_set_rain_radar_trend(
            (uint8_t*) rain_radar_exact_tuple->value->data, 24);
        changed |= persist_set_rain_radar_trend_area(
            (uint8_t*) rain_radar_area_tuple->value->data, 24);
        changed |= persist_set_rain_radar_start(
            (time_t) rain_radar_start_tuple->value->int32);
    }
    *radar_dirty |= changed;
    return true;
}

// Custom radar empty-state text — settings-derived, so it rides the Clay
// message (see clay-payload.js). Empty clears the stored text and the radar
// falls back to its built-in string; persist_set_norain_text also bounds the
// bytes to its 25 B buffer, so a skewed sender can't overrun it.
static bool handle_norain_text(DictionaryIterator *iterator, bool *radar_dirty) {
    Tuple *tuple = dict_find(iterator, MESSAGE_KEY_CLAY_NORAIN_TEXT);
    if (!tuple) {
        return false;
    }
    // A CSTRING tuple; anything else clears back to the built-in default.
    const char *text = (tuple->type == TUPLE_CSTRING) ? tuple->value->cstring : "";
    *radar_dirty |= persist_set_norain_text(text);
    return true;
}
#endif  // WW_RAIN_RADAR

static bool handle_palette(DictionaryIterator *iterator, bool *forecast_dirty,
                           bool *radar_dirty) {
    Tuple *bar_tuple   = dict_find(iterator, MESSAGE_KEY_BAR_PALETTE_UINT8);
#if defined(WW_RAIN_RADAR)
    Tuple *radar_tuple = dict_find(iterator, MESSAGE_KEY_RADAR_PALETTE_UINT8);
    if (!bar_tuple && !radar_tuple) {
        return false;
    }
#else
    // aplite: no radar layer, so the radar palette is never applied.
    (void) radar_dirty;
    if (!bar_tuple) {
        return false;
    }
#endif
    if (bar_tuple) {
        *forecast_dirty |= palette_set_bar(bar_tuple->value->data, (int) bar_tuple->length);
    }
#if defined(WW_RAIN_RADAR)
    if (radar_tuple) {
        *radar_dirty |= palette_set_radar(radar_tuple->value->data, (int) radar_tuple->length);
    }
#endif
    return true;
}

#if defined(WW_CURVE_INSET)
// Per-series forecast curve insets — settings-derived, so the tuple rides the
// Clay message (see clay-payload.js). The phone sends three render-ready px
// values ([FIRST, SECOND, THIRD]: temp's configurable inset, feels-like shares
// it, every other metric 0); the watch stays metric-agnostic and just persists
// them for load_dataset. aplite keeps its frozen constant insets, so the
// handler compiles out there (mirrors the threshold handlers above).
static bool handle_curve_insets(DictionaryIterator *iterator, bool *forecast_dirty) {
    Tuple *tuple = dict_find(iterator, MESSAGE_KEY_CLAY_CURVE_INSET_UINT8);
    if (!tuple) { return false; }
    if (tuple->type != TUPLE_BYTE_ARRAY || tuple->length != CURVE_INSET_BYTES) {
        // Reject atomically; the last good persisted tuple stays intact.
        APP_LOG(APP_LOG_LEVEL_WARNING,
                "Curve-inset tuple malformed (%u bytes) — skipping",
                (unsigned) tuple->length);
        return true;
    }
    // Defensive clamp to the slider's 0..14 px range so a skewed sender can
    // never push a curve's mapping outside the plot.
    uint8_t insets[CURVE_INSET_BYTES];
    for (int i = 0; i < CURVE_INSET_BYTES; i++) {
        const uint8_t v = tuple->value->data[i];
        insets[i] = v > CURVE_INSET_MAX ? CURVE_INSET_MAX : v;
    }
    *forecast_dirty |= persist_set_curve_insets(insets);
    return true;
}
#endif  // WW_CURVE_INSET

// Forecast line styling — settings-derived, so the tuple rides the Clay message
// (see clay-payload.js) instead of costing 44 B on every weather send: four
// int32 scalars (SECONDARY_LINE_COLOR / _FILL_COLOR / _FILL, THIRD_LINE_COLOR)
// became one 4-byte array. It writes exactly the persist slots handle_forecast
// used to write — no new persist keys. NOT compiled out on aplite: every
// platform renders the forecast graph, so every platform needs the colours.
//
// Head (always present): [0] main-metric line, [1] area fill,
// [2] second-metric line, [3] line flags (bit 0 = fill on).
// Tail (optional): bytes [4..9] ARE the NIGHT_COLORS persist blob, byte for
// byte — layout in persist.h. Nothing is repacked or translated on the way
// through, which is the whole reason the night-fill-explicit bit sits in its own
// byte [9] instead of riding byte [3]: one name, one position, both ends.
//
// CONTRACT for growing this tuple: LINE_STYLE_BYTES is a MINIMUM length, not an
// exact one, and everything past it is an optional tail guarded by its own
// `length >= <offset> + <size>` check. A shorter tuple (an older phone bundle, a
// stale fixture) is still applied in full and each absent tail block keeps its
// last good persisted value. Append a new block plus its own length check;
// widening LINE_STYLE_BYTES instead would start REJECTING the tuples those
// shorter senders still emit.
#define LINE_STYLE_BYTES 4
#define LINE_STYLE_FLAG_SECONDARY_FILL 0x01
// Where the NIGHT_COLORS blob starts. Unguarded: the wire layout is the same on
// every platform — only the CONSUMPTION of the tail is colour-only, since B&W
// builds have no persist accessors for it (persist.h) and never paint it.
#define LINE_STYLE_NIGHT_OFFSET 4

static bool handle_line_style(DictionaryIterator *iterator, bool *forecast_dirty) {
    Tuple *tuple = dict_find(iterator, MESSAGE_KEY_CLAY_LINE_STYLE_UINT8);
    if (!tuple) { return false; }
    if (tuple->type != TUPLE_BYTE_ARRAY || tuple->length < LINE_STYLE_BYTES) {
        // Reject atomically; the last good persisted colors stay intact.
        APP_LOG(APP_LOG_LEVEL_WARNING,
                "Line-style tuple malformed (%u bytes) — skipping",
                (unsigned) tuple->length);
        return true;
    }
    // The phone packs each color as a single GColor8 argb byte (the encoding
    // the bar/radar palettes and the threshold blob already use), so build the
    // GColor directly — GColorFromHEX takes 0xRRGGBB and would mangle these.
    const uint8_t *b = tuple->value->data;
    bool changed = false;
    changed |= persist_series_set_color(SERIES_SECOND, (GColor){ .argb = b[0] });
    changed |= persist_set_fill_color((GColor){ .argb = b[1] });
    changed |= persist_series_set_color(SERIES_THIRD, (GColor){ .argb = b[2] });
    changed |= persist_set_line_fill((b[3] & LINE_STYLE_FLAG_SECONDARY_FILL) != 0);
#if defined(PBL_COLOR)
    // Optional tail: store it straight through, so forecast_layer.c reads the
    // wire's own bytes back in a single persist hit.
    if (tuple->length >= LINE_STYLE_NIGHT_OFFSET + NIGHT_COLOR_BYTES) {
        changed |= persist_set_night_colors(&b[LINE_STYLE_NIGHT_OFFSET]);
    }
#endif
    *forecast_dirty |= changed;
    return true;
}

// Parse (bytes→Config, config_wire.c) is separate from apply (Config→persist +
// cache reload + dirty bit, here). config_parse_wire returning false means the
// message carries no config — normal for weather messages.
static bool handle_clay_config(DictionaryIterator *iterator, bool *config_dirty) {
    Config config;
    if (!config_parse_wire(iterator, &config)) {
        return false;
    }
    if (persist_set_config(config)) {
        config_refresh();   // reload the cached config (persist no longer does this)
        *config_dirty = true;
    }
    return true;
}

static bool handle_holidays(DictionaryIterator *iterator, bool *calendar_dirty) {
    Tuple *holidays_tuple = dict_find(iterator, MESSAGE_KEY_HOLIDAYS);
    if (!holidays_tuple || holidays_tuple->length < 8) {
        return false;
    }

    // Packed little-endian: bytes 0-3 = int32 anchor (serial day of bit 0's
    // date), bytes 4-7 = uint32 mask (bit j => date anchor+j is a holiday).
    const uint8_t *d = holidays_tuple->value->data;
    int32_t anchor = (int32_t) ((uint32_t) d[0]
        | ((uint32_t) d[1] << 8)
        | ((uint32_t) d[2] << 16)
        | ((uint32_t) d[3] << 24));
    uint32_t mask = (uint32_t) d[4]
        | ((uint32_t) d[5] << 8)
        | ((uint32_t) d[6] << 16)
        | ((uint32_t) d[7] << 24);

    bool changed = false;
    changed |= persist_set_holiday_anchor(anchor);
    changed |= persist_set_holiday_mask(mask);
    *calendar_dirty |= changed;
    return true;
}

static void inbox_received_callback(DictionaryIterator *iterator, void *context) {
    APP_LOG(APP_LOG_LEVEL_DEBUG, "Inbox received: %u bytes",
            (unsigned) dict_size(iterator));

    bool handled = false;
    bool forecast_dirty = false;  // chart + loading overlay
    bool notice_dirty = false;    // fetch-error / info overlay text
    bool status_dirty = false;    // status row
    bool radar_dirty = false;     // radar chart + top-view availability
    bool config_dirty = false;    // whole window (config feeds every layer)
    bool calendar_dirty = false;  // calendar holiday highlights only
#if defined(WW_RAIN_RADAR)
    // main_window_radar_has_data() is the ONE radar-availability fact the ViewSpec
    // resolves against — the snooze latch/release does NOT feed it. Snapshot it
    // around the handlers so the top view is re-applied only when availability
    // actually flipped (see the radar block below).
    const bool radar_avail_before = main_window_radar_has_data();
#endif
    bool forecast_present = handle_forecast(iterator, &forecast_dirty);
    handled |= forecast_present;
#if defined(WW_FETCH_NOTICE)
    handled |= handle_notice(iterator, &notice_dirty);
    // A forecast only ever arrives from a successful fetch, so any forecast
    // payload clears a lingering error/info overlay (self-heal if a phone→watch
    // clear was ever missed).
    if (forecast_present) {
        notice_dirty |= persist_set_notice_text("");
    }
#endif
    handled |= handle_status(iterator, &status_dirty, &radar_dirty);
    handled |= handle_status_lines(iterator, &status_dirty);
#if defined(WW_THRESHOLD_HIGHLIGHT)
    // aplite renders its status rows from the lean status_row_aplite.c twin, which has
    // no threshold highlighting, so it ignores both threshold tuples and the whole
    // contract module + persist surface drops out (--gc-sections). Mirrors the radar
    // handler below.
    handled |= handle_status_levels(iterator, &status_dirty);
    handled |= handle_thresholds(iterator, &status_dirty);
#endif
    handled |= handle_sun_events(iterator, &forecast_dirty, &status_dirty);
#if defined(WW_RAIN_RADAR)
    // aplite has no radar layer (--gc-sections reaps rain_radar_layer.c), so it
    // ignores inbound radar payloads; the whole radar persist surface drops too.
    handled |= handle_rain_radar(iterator, &radar_dirty);
    // The no-rain text repaints via the same radar_dirty checkpoint below
    // (rain_radar_layer_refresh), so an open radar view redraws on save.
    handled |= handle_norain_text(iterator, &radar_dirty);
#endif
    handled |= handle_palette(iterator, &forecast_dirty, &radar_dirty);
#if defined(WW_CURVE_INSET)
    // aplite keeps its frozen constant curve insets (load_dataset's #else arm),
    // so it ignores the inset tuple and the persist surface drops out.
    handled |= handle_curve_insets(iterator, &forecast_dirty);
#endif
    // Unconditional like handle_palette: the fixture path bundles the styling
    // onto the weather message (fixture-weather.js), so this must not sit
    // behind a "settings message only" branch or fixtures render stale colors.
    handled |= handle_line_style(iterator, &forecast_dirty);
    handled |= handle_clay_config(iterator, &config_dirty);
    handled |= handle_holidays(iterator, &calendar_dirty);
#if defined(WW_RAIN_RADAR)
    // Availability is settled once the handlers above have run; the snooze latch
    // below can't move it (it does not feed the predicate).
    const bool radar_avail_changed =
        radar_avail_before != main_window_radar_has_data();
#endif

    // Release the radar-snooze latch whenever we're awake. Runs after every
    // handler so it can't race the IS_SLEEPING tuple in the same payload.
    // persist_set_radar_snooze is idempotent, so this only does work on the
    // actual wake transition. The latch must NOT be gated on a fresh radar
    // payload: the outbox dedupes the radar category independently, so when
    // the post-wake radar is a dry, merely time-shifted window it is
    // suppressed (overlap matches + tail dry) and no releasing payload ever
    // arrives — which used to leave the snooze screen latched forever. The
    // cached chart is safe to reveal regardless: rain_radar_layer_tick
    // self-advances the window every minute during sleep, so it already
    // holds exactly the data PKJS would (re)send.
    if (!persist_get_is_sleeping()) {
        radar_dirty |= persist_set_radar_snooze(false);
    }

    // The rain-countdown rescan comes FIRST, before anything paints: the countdown is
    // pure data that top_status_layer_refresh() -> recompute_rain_alert() reads, and the
    // status rows are signature-gated (an unchanged signature repaints nothing), so a
    // strip refreshed ahead of the rescan would keep showing the old "Rain in X'" until
    // the next minute tick. The radar payload (or the snooze latch/release) is the
    // countdown's only data-change source, hence the radar_dirty gate.
    // aplite drops the rain-countdown alert (24 KB budget), so it skips the rescan and
    // rain_countdown.c is --gc-sections'd out of that image.
#ifndef PBL_PLATFORM_APLITE
    if (radar_dirty) {
        rain_countdown_refresh(watch_services_now());
    }
#endif
    // The loading/notice overlay rides main_window_refresh() (which the config
    // block below reaches via main_window_apply_top_view), so a weather- or
    // notice-only message is the one case that has to refresh it here — those
    // repaint per-category rather than through a whole-window refresh. The
    // !config_dirty arm only avoids a same-message double refresh (the fixture
    // path bundles claySettings onto the weather message).
    if (!config_dirty && (forecast_dirty || notice_dirty)) {
        loading_layer_refresh();
    }
    if (config_dirty) {
        main_window_apply_theme();   // background first: every render below paints on it
        // Config feeds every layer, and main_window_apply_top_view() covers all of them:
        // it re-applies the view (health_mode may have been changed, e.g. to off, while
        // the alternate view is shown, so the watch falls back to forecast immediately)
        // and ends in the same render + main_window_refresh() the per-category blocks
        // below would do. So it SUBSUMES them — clear the flags it just covered rather
        // than paying for a second layout compute and a second whole-window refresh.
        main_window_apply_top_view();
#if defined(PBL_HEALTH)
        // A changed HR scale (or other graph-affecting setting) must re-derive from the
        // cache, not repaint the already-blanked/rescaled statics from before the save.
        // After the refresh above on purpose: that refresh reports the FORECAST left-axis
        // label width, and the health compute sizes its visible slots from the shared
        // strip that width feeds (bottom_view.h, "wider of both").
        main_window_refresh_health_graph();
#endif
        forecast_dirty = false;
        status_dirty = false;
        calendar_dirty = false;
    }
    if (forecast_dirty) {
        forecast_layer_refresh();
    }
    if (status_dirty) {
        // Every band row renders the same status slots (texts, levels, thresholds,
        // bold), so they all repaint on this checkpoint rather than waiting for the
        // next minute tick; the strip carries slots of its own.
        status_bar_refresh_all();
        top_status_layer_refresh();
    }
    if (radar_dirty) {
#if defined(WW_RAIN_RADAR)
        rain_radar_layer_refresh();
#endif
        // The strip carries the rain-countdown alert, so it repaints for the rescan
        // above — unless an earlier block already refreshed it AFTER that rescan and
        // therefore already carries the fresh countdown. Both do: the config block's
        // whole-window refresh, and the status block's own strip refresh. Nothing the
        // strip reads is produced in between (rain_radar_layer_refresh() above is only
        // a layer_mark_dirty), so a second pass would re-run the battery override, the
        // alert recompute and a full three-slot persist read for an identical picture.
        if (!config_dirty && !status_dirty) {
            top_status_layer_refresh();
        }
#if defined(WW_RAIN_RADAR)
        // Radar availability may have switched — re-evaluate the top view so a cleared
        // radar falls back to the calendar. Only on the actual flip: sleep/snooze do not
        // feed the ViewSpec, so the latch/release alone would cost a full layout compute
        // plus a whole-window refresh for a view that cannot have changed.
        // Not when the config block already ran it: that block sits AFTER every
        // handler, so it already resolved the view against the new radar start epoch.
        // Reachable on the fixture path, where fixture-weather.js bundles claySettings
        // onto the weather message (see above), so a fixture with a radar start epoch
        // replayed over a zero-radar state would otherwise pay two layout computes.
        if (radar_avail_changed && !config_dirty) {
            main_window_apply_top_view();
        }
#endif
    }
    if (calendar_dirty) {
        calendar_layer_refresh();
    }
    if (!handled) {
        APP_LOG(APP_LOG_LEVEL_WARNING, "Bad payload received in app_message.c");
    }
}

static void inbox_dropped_callback(AppMessageResult reason, void *context) {
    APP_LOG(APP_LOG_LEVEL_ERROR, "Message dropped!");
}

void app_message_send_startup_state(bool has_forecast_data) {
    DictionaryIterator *outbox;
    AppMessageResult result = app_message_outbox_begin(&outbox);

    if (result != APP_MSG_OK) {
        APP_LOG(APP_LOG_LEVEL_ERROR, "Unable to begin startup outbox: %d", result);
        return;
    }

    dict_write_uint8(outbox, MESSAGE_KEY_WATCH_HAS_FORECAST_DATA, has_forecast_data ? 1 : 0);
    dict_write_uint8(outbox, MESSAGE_KEY_WATCH_HAS_CONFIG, persist_has_config() ? 1 : 0);
    result = app_message_outbox_send();

    if (result != APP_MSG_OK) {
        APP_LOG(APP_LOG_LEVEL_ERROR, "Unable to send startup state: %d", result);
    }
}

void app_message_init() {
    app_message_register_inbox_received(inbox_received_callback);
    app_message_register_inbox_dropped(inbox_dropped_callback);

    // All changed categories ride in one inbound message (outbox.js bundles
    // them because the channel is half-duplex). The heaviest bundle is DWD +
    // wind: the third line (any metric, including gust) rides alongside the
    // secondary line, plus rain radar + status + sun.
    // The palette and the line styling now ride the Clay message instead
    // (see clay-payload.js; handle_palette / handle_line_style above).
    // test/inbox-size.test.js is the authoritative computation.
    // 528 (was 512): the selectable top-strip middle slot lets City pack up to
    // 19 text bytes where the fixed Date packed none (+19 B worst case, 517 B).
    // 536 (was 528): the threshold-highlight levels byte rides the weather
    // bundle as its own tuple — 1 value byte + the 7-byte tuple header
    // (recorded heaviest bundle now 525 B; headroom 11).
    const int inbox_size = 536;
    const int outbox_size = dict_calc_buffer_size(2, sizeof(uint8_t), sizeof(uint8_t));
    APP_LOG(APP_LOG_LEVEL_INFO, "AppMessage buffer sizes: inbox=%d outbox=%d", inbox_size, outbox_size);
    app_message_open(inbox_size, outbox_size);
    MEMORY_LOG_HEAP("after_app_message_open");
}
