create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  target_version text, -- NULL = everyone (release "What's new" rows use this); '1.7.2' = exact-version match, for version-specific notices only
  title text not null check (length(btrim(title)) > 0),
  body_md text not null check (length(btrim(body_md)) > 0),
  -- Optional embedded poll: array of option strings, e.g. '["Yes","No"]'. NULL = no poll.
  choices jsonb check (choices is null or jsonb_typeof(choices) = 'array')
);

alter table public.news enable row level security;

create policy no_api_access_news
on public.news
for all
to anon, authenticated
using (false)
with check (false);

create table public.news_replies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  news_id bigint not null references public.news (id) on delete cascade,
  account_token_hash text not null,
  app_version text not null,
  message text not null check (length(btrim(message)) > 0 and length(message) <= 1000)
);

alter table public.news_replies enable row level security;

create policy no_api_access_news_replies
on public.news_replies
for all
to anon, authenticated
using (false)
with check (false);

create index news_replies_rate_idx
  on public.news_replies (account_token_hash, created_at);

create table public.news_votes (
  news_id bigint not null references public.news (id) on delete cascade,
  account_token_hash text not null,
  choice_index integer not null check (choice_index >= 0),
  choice_text text not null, -- snapshot of the option string (survives later edits to news.choices)
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(), -- drives the shared 10/day window
  primary key (news_id, account_token_hash)
);

alter table public.news_votes enable row level security;

create policy no_api_access_news_votes
on public.news_votes
for all
to anon, authenticated
using (false)
with check (false);

create index news_votes_rate_idx
  on public.news_votes (account_token_hash, updated_at);

create table public.news_seen (
  account_token_hash text primary key,
  last_seen_news_id bigint not null default 0,
  updated_at timestamp with time zone not null default now()
);

alter table public.news_seen enable row level security;

create policy no_api_access_news_seen
on public.news_seen
for all
to anon, authenticated
using (false)
with check (false);
